services:
  dbt:
    build: .
    volumes:
      - .:/dbt
      - ~/.dbt:/root/.dbt
    environment:
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE:-ACCOUNTADMIN}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA:-ANALYTICS}
    stdin_open: true
    tty: true
    command: ["dbt", "--help"]

  tests:
    build: .
    volumes:
      - .:/dbt
    environment:
      - PYTHONPATH=/dbt
    command: ["pytest", "tests/"]